# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrushExtended < Formula
  desc "Unofficial Crush build with community plugins (otlp, agent-status, periodic-prompts)"
  homepage "https://github.com/aleksclark/crush-modules"
  version "2026.02.03.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.02.03.2/crush-extended_2026.02.03.2_darwin_x86_64.tar.gz"
      sha256 "3ca4bd2b57eab4abe2c75ee0ba579e6dbd8d1b8488002eea716b7ef2954841dc"

      def install
        bin.install "crush"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.02.03.2/crush-extended_2026.02.03.2_darwin_arm64.tar.gz"
      sha256 "b095dd182bbf18b2d09bffdee991eabf23bf686d43d4817a6068fae2396de50f"

      def install
        bin.install "crush"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.02.03.2/crush-extended_2026.02.03.2_linux_x86_64.tar.gz"
      sha256 "a7f7b047b25d692bf51372c7d6e4bd311e26be6c9b02783689783c7c8e30bbba"
      def install
        bin.install "crush"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.02.03.2/crush-extended_2026.02.03.2_linux_arm64.tar.gz"
      sha256 "8c85c637b135d9a8e20e5dbd41c9faa718d77c5f1ca39d9188836d2c86e3401e"
      def install
        bin.install "crush"
      end
    end
  end

  conflicts_with "crush"

  def caveats
    <<~EOS
      WARNING: This is an UNOFFICIAL build of Crush with experimental plugins.
      This is NOT supported by Charm Labs. Use at your own risk.
    EOS
  end

  test do
    system "#{bin}/crush", "--version"
  end
end
