# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrushA2a < Formula
  desc "Unofficial Crush build with the A2A v1.0 protocol plugin (a2a, kuri, otlp, agent-status, periodic-prompts, subagents, tempotown, tavily)"
  homepage "https://github.com/aleksclark/crush-modules"
  version "2026.08.08.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.08.08.1/crush-a2a_2026.08.08.1_darwin_x86_64.tar.gz"
      sha256 "911f035ab89d4fac8d79820450488b891b7900c609e3a85940e9235bf8e845ed"

      define_method(:install) do
        bin.install "crush-a2a"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.08.08.1/crush-a2a_2026.08.08.1_darwin_arm64.tar.gz"
      sha256 "33549bba824ef6954304aae9a7f96d55306ab4396e8cc425dc2172d02ebef94f"

      define_method(:install) do
        bin.install "crush-a2a"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.08.08.1/crush-a2a_2026.08.08.1_linux_x86_64.tar.gz"
      sha256 "e07fc136693151c9f13f8f9db1a85df00e70a003d4033a2ba0edeb9bef5592f6"
      define_method(:install) do
        bin.install "crush-a2a"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.08.08.1/crush-a2a_2026.08.08.1_linux_arm64.tar.gz"
      sha256 "a322f37481da5d298fbd7138f5b5383a139aa635161d898e57320af4c75a99fa"
      define_method(:install) do
        bin.install "crush-a2a"
      end
    end
  end

  def caveats
    <<~EOS
      WARNING: This is an UNOFFICIAL build of Crush with experimental plugins.
      It installs as `crush-a2a` and uses the A2A protocol instead of ACP.
      This is NOT supported by Charm Labs. Use at your own risk.
    EOS
  end

  test do
    system "#{bin}/crush-a2a", "--version"
  end
end
