# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrushA2a < Formula
  desc "Unofficial Crush build with the A2A v1.0 protocol plugin (a2a, kuri, otlp, agent-status, periodic-prompts, subagents, tempotown, tavily)"
  homepage "https://github.com/aleksclark/crush-modules"
  version "2026.09.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.09.10.1/crush-a2a_2026.09.10.1_darwin_x86_64.tar.gz"
      sha256 "41788679f472198dfab0765c709ab6d72d5b60934dc5fe16554887945174d793"

      define_method(:install) do
        bin.install "crush-a2a"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.09.10.1/crush-a2a_2026.09.10.1_darwin_arm64.tar.gz"
      sha256 "6df222709193d891c529669acc7f8bb3c32cc4ce689390226c31e335487f84a3"

      define_method(:install) do
        bin.install "crush-a2a"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.09.10.1/crush-a2a_2026.09.10.1_linux_x86_64.tar.gz"
      sha256 "e5b0ffd402cd454d7cf8b996e0936fd7fd5bb24cfb3799db60196c816c71120c"
      define_method(:install) do
        bin.install "crush-a2a"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.09.10.1/crush-a2a_2026.09.10.1_linux_arm64.tar.gz"
      sha256 "5564db8380957e6eda50d1166b4f7c02d9f71b6a1ee4533c3940120264622c9f"
      define_method(:install) do
        bin.install "crush-a2a"
      end
    end
  end

  def caveats
    <<~EOS
      WARNING: This is an UNOFFICIAL build of Crush with experimental plugins.
      It installs as `crush-a2a` and uses the A2A protocol instead of ACP.
      This is NOT supported by Charm Labs. Use at your own risk.
    EOS
  end

  test do
    system "#{bin}/crush-a2a", "--version"
  end
end
