# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrushExtended < Formula
  desc "Unofficial Crush build with community plugins (acp, kuri, otlp, agent-status, periodic-prompts, subagents, tempotown, tavily)"
  homepage "https://github.com/aleksclark/crush-modules"
  version "2026.08.27.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.08.27.1/crush-extended_2026.08.27.1_darwin_x86_64.tar.gz"
      sha256 "a68beb2498308dd6e8d309440343dbaca3f1b9bcead7dc550776dfaa084ed8a0"

      define_method(:install) do
        bin.install "crush"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.08.27.1/crush-extended_2026.08.27.1_darwin_arm64.tar.gz"
      sha256 "4e0f3f1bfb5c5c87b2c7378dbfc7c192ad606f7e9e52a89e01a8e7bc1d09979d"

      define_method(:install) do
        bin.install "crush"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.08.27.1/crush-extended_2026.08.27.1_linux_x86_64.tar.gz"
      sha256 "946df2a31485ee32bf92ef6535e302968aab6ec98fc1b0dc8a45aef2a7e6efe2"
      define_method(:install) do
        bin.install "crush"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.08.27.1/crush-extended_2026.08.27.1_linux_arm64.tar.gz"
      sha256 "1fad44371659718615d5174546d88324095c5a0e64dba5c6eab961c1d8b1d236"
      define_method(:install) do
        bin.install "crush"
      end
    end
  end

  conflicts_with "crush"

  def caveats
    <<~EOS
      WARNING: This is an UNOFFICIAL build of Crush with experimental plugins.
      This is NOT supported by Charm Labs. Use at your own risk.
    EOS
  end

  test do
    system "#{bin}/crush", "--version"
  end
end
