# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrushExtended < Formula
  desc "Unofficial Crush build with community plugins (acp, kuri, otlp, agent-status, periodic-prompts, subagents, tempotown, tavily)"
  homepage "https://github.com/aleksclark/crush-modules"
  version "2026.04.29.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.04.29.2/crush-extended_2026.04.29.2_darwin_x86_64.tar.gz"
      sha256 "5a42477c68bb6c7cc3cc87a49140b1393d01c3b74bc7ba337c7acbc06d483419"

      define_method(:install) do
        bin.install "crush"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.04.29.2/crush-extended_2026.04.29.2_darwin_arm64.tar.gz"
      sha256 "36aee9cce5cbd17b481f3938a6c87cf52160c76a06c0511a80299c75c763c200"

      define_method(:install) do
        bin.install "crush"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.04.29.2/crush-extended_2026.04.29.2_linux_x86_64.tar.gz"
      sha256 "de5f146f5aead6ce52d990ff3091061ffef66a2c8206345f6f75e7ba8bb66254"
      define_method(:install) do
        bin.install "crush"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.04.29.2/crush-extended_2026.04.29.2_linux_arm64.tar.gz"
      sha256 "d1ec795a8fca84c9587e51ef184f5f91fdf987c41cf143b754b340d70c0a873a"
      define_method(:install) do
        bin.install "crush"
      end
    end
  end

  conflicts_with "crush"

  def caveats
    <<~EOS
      WARNING: This is an UNOFFICIAL build of Crush with experimental plugins.
      This is NOT supported by Charm Labs. Use at your own risk.
    EOS
  end

  test do
    system "#{bin}/crush", "--version"
  end
end
