# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xcrush < Formula
  desc "Unofficial build tool for creating custom Crush distributions with plugins"
  homepage "https://github.com/aleksclark/crush-modules"
  version "2026.03.09.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.03.09.1/xcrush_2026.03.09.1_darwin_x86_64.tar.gz"
      sha256 "fbe4d78fa5a96cb3fcb18e754718cfccabebe05a7d22ef1029b66c62472fa7ef"

      define_method(:install) do
        bin.install "xcrush"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.03.09.1/xcrush_2026.03.09.1_darwin_arm64.tar.gz"
      sha256 "315a7b34d06d0480c8d8443069071711203709fc4954fe629bedc904392c6da3"

      define_method(:install) do
        bin.install "xcrush"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.03.09.1/xcrush_2026.03.09.1_linux_x86_64.tar.gz"
      sha256 "08c835b4a542a4cb02e362b54eaa7c508a87ed3c728e12c140c1898bcd96a8a7"
      define_method(:install) do
        bin.install "xcrush"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.03.09.1/xcrush_2026.03.09.1_linux_arm64.tar.gz"
      sha256 "2d4bcfddf4e9d7219b2d2eadcc0fbd82b7b4d9d46a1b310e8e44b95cc7aa368f"
      define_method(:install) do
        bin.install "xcrush"
      end
    end
  end

  test do
    system "#{bin}/xcrush", "--version"
  end
end
