# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xcrush < Formula
  desc "Unofficial build tool for creating custom Crush distributions with plugins"
  homepage "https://github.com/aleksclark/crush-modules"
  version "2026.04.09.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.04.09.4/xcrush_2026.04.09.4_darwin_x86_64.tar.gz"
      sha256 "23798ea4b3b54a1caac2b171a7d7df24ab56d805af682d383e1abb890775a538"

      define_method(:install) do
        bin.install "xcrush"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.04.09.4/xcrush_2026.04.09.4_darwin_arm64.tar.gz"
      sha256 "7830b1b453544999b2cb47bda863c7285e374ceb3cd4d739b0a7497e0650e55e"

      define_method(:install) do
        bin.install "xcrush"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.04.09.4/xcrush_2026.04.09.4_linux_x86_64.tar.gz"
      sha256 "0c0ad47c40ef0f3dd27ee125ac6342f96f0eda11c27f5cc68d5148a5b843fe3a"
      define_method(:install) do
        bin.install "xcrush"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aleksclark/crush-modules/releases/download/2026.04.09.4/xcrush_2026.04.09.4_linux_arm64.tar.gz"
      sha256 "763e436d6661838128bfe31543311c6d01c0e7c4d85f0df5b5d3f27f803fc0f0"
      define_method(:install) do
        bin.install "xcrush"
      end
    end
  end

  test do
    system "#{bin}/xcrush", "--version"
  end
end
